CREATE TABLE Venue (
    venue_id INTEGER PRIMARY KEY UNIQUE NOT NULL,
    name VARCHAR(100) NOT NULL,
    address VARCHAR(100) NOT NULL,
    city VARCHAR(50) NOT NULL,
    country VARCHAR(50) NOT NULL,
    capacity INTEGER NOT NULL,
    surface VARCHAR(25) NOT NULL,
    image VARCHAR(150) NOT NULL
);

CREATE TABLE Team (
    team_id INTEGER PRIMARY KEY UNIQUE NOT NULL,
    name VARCHAR(100) NOT NULL,
    code VARCHAR(25) NOT NULL,
    country VARCHAR(50) NOT NULL,
    founded INTEGER NOT NULL,
    national BOOLEAN NOT NULL,
    logo VARCHAR(150) NOT NULL,
    games_played_home INTEGER NOT NULL,
    games_played_away INTEGER NOT NULL,
    games_played_total INTEGER NOT NULL,
    wins_home INTEGER NOT NULL,
    wins_away INTEGER NOT NULL,
    wins_total INTEGER NOT NULL,
    draws_home INTEGER NOT NULL,
    draws_away INTEGER NOT NULL,
    draws_total INTEGER NOT NULL,
    losses_home INTEGER NOT NULL,
    losses_away INTEGER NOT NULL,
    losses_total INTEGER NOT NULL,
    goals_for_home INTEGER NOT NULL,
    goals_for_away INTEGER NOT NULL,
    goals_for_total INTEGER NOT NULL,
    segments_for JSONB NOT NULL,
    goals_against_home INTEGER NOT NULL,
    goals_against_away INTEGER NOT NULL,
    goals_against_total INTEGER NOT NULL,
    segments_against JSONB NOT NULL, 
    biggest_win_home VARCHAR(10) NOT NULL,
    biggest_win_away VARCHAR(10) NOT NULL,
    biggest_loss_home VARCHAR(10) NOT NULL,
    biggest_loss_away VARCHAR(10) NOT NULL,
    clean_sheet_home INTEGER NOT NULL,
    clean_sheet_away INTEGER NOT NULL,
    clean_sheet_total INTEGER NOT NULL,
    failed_to_score_home INTEGER NOT NULL,
    failed_to_score_away INTEGER NOT NULL,
    failed_to_score_total INTEGER NOT NULL,
    penalty_scored INTEGER NOT NULL,
    penalty_missed INTEGER NOT NULL,
    yellow_cards JSONB NOT NULL,  
    red_cards JSONB NOT NULL,      
    venue_id INTEGER REFERENCES Venue(venue_id) ON DELETE SET NULL
);

CREATE TABLE Player (
    player_id INTEGER PRIMARY KEY UNIQUE NOT NULL,
    name VARCHAR(100) NOT NULL,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    age INTEGER NOT NULL,
    position VARCHAR(4) NOT NULL,
    birth JSONB NOT NULL,
    nationality VARCHAR(50) NOT NULL,
    height INTEGER NOT NULL,
    weight INTEGER NOT NULL,
    injured BOOLEAN NOT NULL,
    photo VARCHAR(150) NOT NULL,
    games_appearances INTEGER NOT NULL,
    games_lineups INTEGER NOT NULL,
    minutes_played_total INTEGER NOT NULL,
    rating DECIMAL(2, 2) CHECK (rating >= 0 AND rating <= 10) NOT NULL,
    substitutes_in INTEGER NOT NULL,
    substitutes_out INTEGER NOT NULL,
    bench INTEGER NOT NULL,
    shots_on INTEGER NOT NULL,
    shots_total INTEGER NOT NULL,
    goals_total INTEGER NOT NULL,
    goals_conceded INTEGER NOT NULL,
    goals_assists INTEGER NOT NULL,
    goals_saved INTEGER NOT NULL,
    passes_total INTEGER NOT NULL,
    passes_key INTEGER NOT NULL,
    passes_accuracy DECIMAL(5, 2) CHECK (passes_accuracy >= 0 AND passes_accuracy <= 100) NOT NULL,
    tackles_total INTEGER NOT NULL,
    tackles_blocks INTEGER NOT NULL,
    tackles_interceptions INTEGER NOT NULL,
    duels_total INTEGER NOT NULL,
    duels_won_total INTEGER NOT NULL,
    dribbles_attempts_total INTEGER NOT NULL,
    dribbles_success_total INTEGER NOT NULL,
    dribbles_past_total INTEGER NOT NULL,
    fouls_drawn_total INTEGER NOT NULL,
    fouls_committed_total INTEGER NOT NULL,
    cards_yellow_total INTEGER NOT NULL,
    cards_red_total INTEGER NOT NULL,
    penalty_won_total INTEGER NOT NULL,
    penalty_committed_total INTEGER NOT NULL,
    penalty_scored_total INTEGER NOT NULL,
    penalty_missed_total INTEGER NOT NULL,
    penalty_saved_total INTEGER NOT NULL,
    team_id INTEGER REFERENCES Team(team_id) ON DELETE SET NULL
);

CREATE TABLE TeamsHistoric (
    player_id INTEGER REFERENCES Player(player_id) ON DELETE CASCADE NOT NULL,
    team_id INTEGER REFERENCES Team(team_id) ON DELETE CASCADE NOT NULL,
    seasons INTEGER NOT NULL,
    PRIMARY KEY (player_id, team_id)
);

CREATE TABLE Game (
    game_id INTEGER PRIMARY KEY UNIQUE NOT NULL,
    referee VARCHAR(50) NOT NULL,
    timezone VARCHAR(10) NOT NULL,
    date TIMESTAMP(6) NOT NULL,
    first_period TIMESTAMP(6) NOT NULL,
    second_period TIMESTAMP(6) NOT NULL,
    score JSONB NOT NULL,
    home_team_goals INTEGER NOT NULL,
    away_team_goals INTEGER NOT NULL,
    venue_id INTEGER REFERENCES Venue(venue_id) ON DELETE CASCADE NOT NULL,
    home_team_id INTEGER REFERENCES Team(team_id) ON DELETE CASCADE NOT NULL,
    away_team_id INTEGER REFERENCES Team(team_id) ON DELETE CASCADE NOT NULL,
    winner_team_id INTEGER REFERENCES Team(team_id) ON DELETE SET NULL NOT NULL
);

CREATE TABLE Injuries (
    player_id INTEGER REFERENCES Player(player_id) ON DELETE CASCADE NOT NULL,
    game_id INTEGER REFERENCES Game(game_id) ON DELETE CASCADE NOT NULL,
    type VARCHAR(50) CHECK (type IN ('Missing Fixture', 'Questionable')) NOT NULL,
    reason VARCHAR(100) NOT NULL,
    PRIMARY KEY (player_id, game_id)
);

-- SG stands for "Single Game"
CREATE TABLE SGTeamStatistics (
    game_id INTEGER REFERENCES Game(game_id) ON DELETE CASCADE NOT NULL,
    team_id INTEGER REFERENCES Team(team_id) ON DELETE CASCADE NOT NULL,
    shots_on_goal INTEGER NOT NULL,
    shots_off_goal INTEGER NOT NULL,
    total_shots INTEGER NOT NULL,
    blocked_shots INTEGER NOT NULL,
    shots_insidebox INTEGER NOT NULL,
    shots_outsidebox INTEGER NOT NULL,
    fouls INTEGER NOT NULL,
    corner_kicks INTEGER NOT NULL,
    offsides INTEGER NOT NULL,
    yellow_cards INTEGER NOT NULL,
    red_cards INTEGER NOT NULL,
    goalkeeper_saves INTEGER NOT NULL,
    total_passes INTEGER NOT NULL,
    passes_accurate INTEGER NOT NULL,
    ball_possession DECIMAL(5, 2) CHECK (ball_possession >= 0 AND ball_possession <= 100) NOT NULL,
    passes_percentage DECIMAL(5, 2) CHECK (passes_percentage >= 0 AND passes_percentage <= 100) NOT NULL,
    expected_goals DECIMAL(5, 2) CHECK (expected_goals >= 0 AND expected_goals <= 100) NOT NULL,
    PRIMARY KEY (game_id, team_id)
);

-- SG stands for "Single Game"
CREATE TABLE SGPlayerStatistics (
    player_id INTEGER REFERENCES Player(player_id) ON DELETE CASCADE NOT NULL,
    game_id INTEGER REFERENCES Game(game_id) ON DELETE CASCADE NOT NULL,
    player_number INTEGER NOT NULL,
    position CHAR(5) NOT NULL,
    rating DECIMAL(2, 2) CHECK (rating >= 0 AND rating <= 10) NOT NULL,
    captain BOOLEAN NOT NULL,
    substitute BOOLEAN NOT NULL,
    offsides INTEGER NOT NULL,
    shots_on INTEGER NOT NULL,
    shots_total INTEGER NOT NULL,
    goals_total INTEGER NOT NULL,
    goals_conceded INTEGER NOT NULL,
    goals_assists INTEGER NOT NULL,
    goals_saves INTEGER NOT NULL,
    passes_total INTEGER NOT NULL,
    passes_key INTEGER NOT NULL,
    passes_accuracy DECIMAL(5, 2) CHECK (passes_accuracy >= 0 AND passes_accuracy <= 100) NOT NULL,
    tackles_total INTEGER NOT NULL,
    blocks INTEGER NOT NULL,
    interceptions INTEGER NOT NULL,
    duels_total INTEGER NOT NULL,
    duels_won INTEGER NOT NULL,
    dribbles_attempts INTEGER NOT NULL,
    dribbles_success INTEGER NOT NULL,
    dribbles_past INTEGER NOT NULL,
    fouls_drawn INTEGER NOT NULL,
    fouls_committed INTEGER NOT NULL,
    yellow_cards INTEGER NOT NULL,
    red_cards INTEGER NOT NULL,
    penalty_won INTEGER NOT NULL,
    penalty_committed INTEGER NOT NULL,
    penalty_scored INTEGER NOT NULL,
    penalty_missed INTEGER NOT NULL,
    penalty_saved INTEGER NOT NULL,
    PRIMARY KEY (player_id, game_id)
);